name: CauldronWars
version: 1.01
author: Mobkinz78
main: com.redstoneoinkcraft.me.Main
description: A minigame plugin, called Cauldron Wars, for Redstone Oinkcraft!
commands:
  cauldronwars:
    description: The main command argument for everything
    aliases: [cw, cwars]
  cwarsarena:
    description: The command argument for creating an arena
  cwshout:
    description: Let's players shout to public chat
permissions:
  cauldronwars.use:
    description: Base permission for cauldronwars.
  cauldronwars.sign:
    description: Allows a player to create a sign for cauldron wars.
  cauldronwars.arena:
    description: Lets a player use the command arguments found with ArenaCreateCommand.
  cauldronwars.kit:
    description: Lets a player use the kit command to choose a kit.
  cauldronwars.kit.donor:
    description: Lets players use donor kits. To be added later.
  cauldronwars.sign.create:
    description: Lets players create signs.
  cauldronwars.leave:
    description: Lets players leave a game they are in.
  cauldronwars.break:
    description: Lets players place/break blocks in the minigame world.